In [1]:
import polars as pl


pdb_af3 = pl.read_parquet("../../data/pdb/triad/staged/pdb_triad.af3_rmsd.parquet")

In [4]:
pdb_af3.filter(pl.col("pdb") == "8trl")

shape: (0, 97)
┌──────────┬─────────┬─────────┬───────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ job_name ┆ cognate ┆ peptide ┆ mhc_class ┆ … ┆ cdr_rmsd_a ┆ peptide_rm ┆ mhc_rmsd_a ┆ tcr_rmsd_a │
│ ---      ┆ ---     ┆ ---     ┆ ---       ┆   ┆ f3_4       ┆ sd_af3_4   ┆ f3_4       ┆ f3_4       │
│ str      ┆ bool    ┆ str     ┆ str       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│          ┆         ┆         ┆           ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞══════════╪═════════╪═════════╪═══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
└──────────┴─────────┴─────────┴───────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [9]:
import requests
from pathlib import Path

url = "https://files.rcsb.org/download/"

for row in pdb_af3.iter_rows(named=True):
    id = row["pdb"]

    r = requests.get(url + id.upper() + ".pdb", allow_redirects=True)

    with open("dump" + "/" + id.upper() + ".pdb", "wb") as f:
        f.write(r.content)

In [27]:
import MDAnalysis as mda
from MDAnalysis.lib.util import convert_aa_code
from collections import defaultdict

invalid = []

for row in pdb_af3.iter_rows(named=True):
    id = row["pdb"]
    # print(id)

    try:
        u = mda.Universe("dump/" + id.upper() + ".pdb")
    except Exception:
        u = mda.Universe("dump/" + id.upper() + ".cif")

    d = {"pdb": id, "invalid": []}

    for res in u.select_atoms("not water").residues:

        try:
            convert_aa_code(res.resname)
        except Exception:
            # print(res.resname)
            d["invalid"].append(res.resname)

    if len(d["invalid"]):
        invalid.append(d)

invalid = pl.DataFrame(invalid)

/tgen_labs/altin/miniconda3/envs/tcrtrifold-experiments/lib/python3.12/site-packages/MDAnalysis/topology/PDBParser.py:384: UserWarning: Element information is missing, elements attribute will not be populated. If needed these can be guessed using universe.guess_TopologyAttrs(context='default', to_guess=['elements']).
  warnings.warn("Element information is missing, elements attribute "
/tgen_labs/altin/miniconda3/envs/tcrtrifold-experiments/lib/python3.12/site-packages/MDAnalysis/coordinates/PDB.py:465: UserWarning: 1 A^3 CRYST1 record, this is usually a placeholder. Unit cell dimensions will be set to None.
  warnings.warn("1 A^3 CRYST1 record,"

In [41]:
invalid

shape: (84, 2)
┌──────┬─────────────────────────┐
│ pdb  ┆ invalid                 │
│ ---  ┆ ---                     │
│ str  ┆ list[str]               │
╞══════╪═════════════════════════╡
│ 4may ┆ ["SO4"]                 │
│ 4p4k ┆ ["NAG", "NAG", … "0BE"] │
│ 6dfs ┆ ["NAG"]                 │
│ 4grl ┆ ["NAG"]                 │
│ 6dfx ┆ ["NAG", "NAG", … "NAG"] │
│ …    ┆ …                       │
│ 3ffc ┆ ["CD", "CL", … "CL"]    │
│ 3gsn ┆ ["SO4", "CL"]           │
│ 4ozf ┆ ["NAG", "NAG"]          │
│ 5men ┆ ["EDO", "EDO", … "SO4"] │
│ 1ao7 ┆ ["EMC", "EMC"]          │
└──────┴─────────────────────────┘

In [40]:
from xlsxwriter import Workbook

with Workbook("invalid_codes.xlsx") as wb:

    invalid.sort(by="pdb").write_excel(workbook=wb, worksheet="invalid_pdb")
    invalid.explode("invalid").select("invalid").unique().write_excel(
        workbook=wb, worksheet="unique_invalid"
    )