In [2]:
from tcrtrifold.utils import FORMAT_ANTIGEN_COLS
import polars as pl

assay_type = pl.read_parquet("../../data/iedb_meta/assay_type.parquet")
receptor_reference = pl.read_parquet("../../data/iedb_meta/receptor_reference.parquet")


iedb_II_annot = pl.read_parquet(
    "../../data/iedb_II_full/triad/iedb_II_triad.annotated.parquet"
)

iedb_II_pdb_pmhc = (
    iedb_II_annot.filter(pl.col("pmhc_in_pdb")).select(FORMAT_ANTIGEN_COLS).unique()
)

iedb_II_pdb_triad = (
    iedb_II_annot.explode("receptor_id")
    .explode("references")
    .join(
        receptor_reference,
        left_on=["references", "receptor_id"],
        right_on=["reference_id", "receptor_id"],
    )
)

iedb_II = pl.read_parquet(
    "../../data/iedb_II/triad/iedb_II_triad.conf_af3.parquet"
).join(
    iedb_II_pdb_triad.select("job_name", "assay_type", "triad_in_pdb"), on="job_name"
)

iedb_I_annot = pl.read_parquet(
    "../../data/iedb_I_full/triad/iedb_I_triad.annotated.parquet"
)

iedb_I_pdb_pmhc = (
    iedb_II_annot.filter(pl.col("pmhc_in_pdb")).select(FORMAT_ANTIGEN_COLS).unique()
)

iedb_I_pdb_triad = (
    iedb_I_annot.explode("receptor_id")
    .explode("references")
    .join(
        receptor_reference,
        left_on=["references", "receptor_id"],
        right_on=["reference_id", "receptor_id"],
    )
)

iedb_I = pl.read_parquet(
    "../../data/iedb_I/triad/iedb_I_triad.conf_af3.parquet"
).join(
    iedb_I_pdb_triad.select("job_name", "assay_type", "triad_in_pdb"), on="job_name"
)

## Summary nums

In [9]:
iedb_I.filter(pl.col("triad_in_pdb")).select("job_name").unique().height

393

In [10]:
iedb_II.filter(pl.col("triad_in_pdb")).select("job_name").unique().height

63

In [6]:
iedb_I.filter(~pl.col("triad_in_pdb")).filter(pl.col("assay_type") == "x-ray crystallography").select("job_name").item()

'121f50b609621ebe92777820dad90eb9'

In [36]:
iedb_II.filter(
    pl.col("assay_type") == "x-ray crystallography"
).filter(~pl.col("triad_in_pdb")).select("mean_p_tcr_pae").to_series().to_numpy()

iedb_II.filter(
    pl.col("assay_type") == "x-ray crystallography"
).filter(pl.col("triad_in_pdb")).select("mean_p_tcr_pae").to_series().to_numpy()

array([18.04374123,  5.43211937, 11.87347412,  5.33814955,  5.11006117,
        4.50323057,  7.79586029,  7.50704002, 10.60125923,  5.37580204,
       11.39432812, 22.31526184,  5.66939402, 23.68894958,  4.81122828,
       21.07127571,  5.32468271, 10.86191559, 14.77916336, 13.48510456,
        9.68382168,  5.36084175, 10.53259087, 16.21871376, 16.21871376,
       16.21871376,  9.67007446, 18.21819878,  8.86339378,  5.08924675,
        4.33785868,  5.99226379,  7.38107443,  7.65907764,  5.32265091,
        5.30932617])

shape: (36, 81)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ job_name   ┆ cognate ┆ peptide   ┆ mhc_class ┆ … ┆ min_tcr_m ┆ peptide_m ┆ assay_typ ┆ triad_in_ │
│ ---        ┆ ---     ┆ ---       ┆ ---       ┆   ┆ hc_pae    ┆ ean_pLDDT ┆ e         ┆ pdb       │
│ str        ┆ bool    ┆ str       ┆ str       ┆   ┆ ---       ┆ _II       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆           ┆   ┆ f64       ┆ ---       ┆ str       ┆ bool      │
│            ┆         ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0da5bca165 ┆ true    ┆ GQVELGGGN ┆ II        ┆ … ┆ 1.41      ┆ 54.996091 ┆ x-ray cry ┆ true      │
│ be2277f154 ┆         ┆ AVEVCK    ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ c5c6907522 ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0eab4f1d03 ┆ true    ┆ RFYKTLRAE ┆ II        ┆ … ┆ 1.26      ┆ 92.937424 ┆ x-ray cry ┆ true      │
│ 1514c4d474 ┆         ┆ QASQ      ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ 9bc1a4f6e1 ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 101037d801 ┆ true    ┆ APSGEGSFQ ┆ II        ┆ … ┆ 1.52      ┆ 86.067888 ┆ x-ray cry ┆ true      │
│ a41030afab ┆         ┆ PSQENPQGS ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ ae721c77ec ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1a6333fa4b ┆ true    ┆ MVVQSELPY ┆ II        ┆ … ┆ 1.19      ┆ 95.467119 ┆ x-ray cry ┆ true      │
│ caee25755d ┆         ┆ PE        ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ 392c7a9b00 ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1cdffdbd2b ┆ true    ┆ PKYVKQNTL ┆ II        ┆ … ┆ 1.2       ┆ 94.310898 ┆ x-ray cry ┆ true      │
│ 5355468b39 ┆         ┆ KLAT      ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ c60626bfd6 ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ f2d61d5804 ┆ true    ┆ RFYKTLRAE ┆ II        ┆ … ┆ 1.24      ┆ 91.217344 ┆ x-ray cry ┆ true      │
│ 5c3213c5c6 ┆         ┆ QASQ      ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ 640ac60bd4 ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ f444d82f48 ┆ true    ┆ GELIGILNA ┆ II        ┆ … ┆ 1.4       ┆ 92.374003 ┆ x-ray cry ┆ true      │
│ 19fc5a7caa ┆         ┆ AKVPAD    ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ 4bf66a1549 ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ f777496168 ┆ true    ┆ LVEELYLVA ┆ II        ┆ … ┆ 1.16      ┆ 92.658584 ┆ x-ray cry ┆ true      │
│ 164c075dc2 ┆         ┆ GEEGC     ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ c76ae6358e ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ f93d233143 ┆ true    ┆ GPQQSFPEQ ┆ II        ┆ … ┆ 1.51      ┆ 92.903342 ┆ x-ray cry ┆ true      │
│ 8af4f4356d ┆         ┆ EA        ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ 1cf38eac85 ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ fb295a801f ┆ true    ┆ RFYKTLRAE ┆ II        ┆ … ┆ 1.29      ┆ 92.918129 ┆ x-ray cry ┆ true      │
│ 69b721f290 ┆         ┆ QASQ      ┆           ┆   ┆           ┆           ┆ stallogra ┆           │
│ dc9413568d ┆         ┆           ┆           ┆   ┆           ┆           ┆ phy       ┆           │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
pl.read_parquet("../../data/iedb_II/triad/iedb_II_triad.conf_af3.parquet").filter(
    pl.col("cognate")
).explode("receptor_id").join(assay_type, on="receptor_id").filter(
    pl.col("assay_type") == "x-ray crystallography"
).select(
    "job_name"
).unique()

shape: (54, 1)
┌─────────────────────────────────┐
│ job_name                        │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ cf121d1f52814846fc07a64d294260… │
│ 061c8ad983dbd76ee0bfd8065e83e1… │
│ 7e8af51467a1660bde66e8b51a47e1… │
│ 8820f354b4abe3df9acbd96902f5cf… │
│ f93d2331438af4f4356d1cf38eac85… │
│ …                               │
│ 89095d1cb5f93fbbbf73eddd813e56… │
│ c7954511abf812e94c78d48d9ec1b8… │
│ 8071a1d24c713564eb8f87a13dff8d… │
│ b8632762b6386b639854d53244ce5c… │
│ a1b75d3c4d00dbb9e09bfbc6a46975… │
└─────────────────────────────────┘

In [ ]:
pl.read_parquet("../../data/iedb_II/triad/iedb_II_triad.conf_af3.parquet").filter(
    pl.col("cognate")
).explode("receptor_id").explode("references").join(
    receptor_reference,
    left_on=["references", "receptor_id"],
    right_on=["reference_id", "receptor_id"],
).filter(
    pl.col("assay_type") == "x-ray crystallography"
).select(
    "job_name"
).unique()

shape: (46, 1)
┌─────────────────────────────────┐
│ job_name                        │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ f777496168164c075dc2c76ae6358e… │
│ fb295a801f69b721f290dc9413568d… │
│ 7e8af51467a1660bde66e8b51a47e1… │
│ cedf34bd3c1ad711c9e71d3018068e… │
│ f2d61d58045c3213c5c6640ac60bd4… │
│ …                               │
│ a8f0fb7e6177b58a8c9577ad1fce8b… │
│ c7954511abf812e94c78d48d9ec1b8… │
│ 1a6333fa4bcaee25755d392c7a9b00… │
│ 81e23275b4df442ad5230d3319a446… │
│ 20f085497475c83d78c84108ddecee… │
└─────────────────────────────────┘

In [ ]:
iedb_II.filter(pl.col("assay_type") == "x-ray crystallography").select(
    "job_name"
).unique()

shape: (54, 1)
┌─────────────────────────────────┐
│ job_name                        │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ 0da5bca165be2277f154c5c6907522… │
│ 40a5bc0bd375733d6c98789dbc83e3… │
│ b2677109639e627973a47b2d06a7fd… │
│ 8994534501247aa06ce81d427997be… │
│ 20f085497475c83d78c84108ddecee… │
│ …                               │
│ 0eab4f1d031514c4d4749bc1a4f6e1… │
│ 8071a1d24c713564eb8f87a13dff8d… │
│ 1cdffdbd2b5355468b39c60626bfd6… │
│ b193124d6600d895eb4cfc6cb14172… │
│ f777496168164c075dc2c76ae6358e… │
└─────────────────────────────────┘

In [19]:
iedb_II_pdb_triad.filter(pl.col("assay_type") == "x-ray crystallography").filter(
    ~pl.col("triad_in_pdb")
)

shape: (18, 34)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ job_name   ┆ cognate ┆ peptide   ┆ mhc_class ┆ … ┆ peptide_a ┆ triad_in_ ┆ triad_mat ┆ assay_typ │
│ ---        ┆ ---     ┆ ---       ┆ ---       ┆   ┆ lignments ┆ pdb       ┆ ches      ┆ e         │
│ str        ┆ bool    ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆           ┆   ┆ list[str] ┆ bool      ┆ list[str] ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3bf8262290 ┆ true    ┆ QRCRVHFMR ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ d0427d7005 ┆         ┆ NLYTAV    ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ c292d6d326 ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 71cfe29319 ┆ true    ┆ ALAVLHFYP ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ f368c4def1 ┆         ┆ DKGAKN    ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ 60dae775c0 ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 061c8ad983 ┆ true    ┆ QRCRVHFLR ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ dbd76ee0bf ┆         ┆ NVLAQV    ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ d8065e83e1 ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ b8632762b6 ┆ true    ┆ DIALNLPRR ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ 386b639854 ┆         ┆ I         ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ d53244ce5c ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ ff1914b08d ┆ true    ┆ LIHVNIPKK ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ eb85107f1c ┆         ┆ I         ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ e6206e9e42 ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ a184bfb77d ┆ true    ┆ ITREEKPAV ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ f61fe6de02 ┆         ┆ TAAPKK    ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ 05b171bcc8 ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 171154955a ┆ true    ┆ TLDISNNRL ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ 6d6006f1a3 ┆         ┆ ESLPAH    ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ 9b5446416c ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ e33658dc93 ┆ true    ┆ AHPADPGSR ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ 958df61948 ┆         ┆ PHLIRLFSR ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ ecde47492c ┆         ┆ DA        ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ d7ad05c556 ┆ true    ┆ TTSEDNEVF ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ c96bb954c3 ┆         ┆ GEADANQNN ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ d91afa7ecb ┆         ┆ GTSS      ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 061c8ad983 ┆ true    ┆ QRCRVHFLR ┆ II        ┆ … ┆ null      ┆ false     ┆ null      ┆ x-ray cry │
│ dbd76ee0bf ┆         ┆ NVLAQV    ┆           ┆   ┆           ┆           ┆           ┆ stallogra │
│ d8065e83e1 ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ phy       │
│ …          ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘